package com.epam.yoda.config.enums;

/**
 * @author Sergey Mikhluk.
 */
public enum EPageParameter {
    COMMAND, SUB_FILTER_CATEGORY, SUB_FILTER_STATUS, SUB_FILTER_ACTIVITY, SUB_FILTER_TASK_NAME, SUB_FILTER_ORDER_BY,
    CHOSEN_ELEMENT_ID, CURRENT_TASK_NAME, CURRENT_TASK_CONTENT, CURRENT_TASK_CATEGORY, CURRENT_TASK_ACTIVITY,
    CURRENT_TASK_PRIORITY, CURRENT_TASK_STATUS, CURRENT_TASK_DEADLINE,
    CURRENT_USER_LOGIN, CURRENT_USER_PASSWORD, CURRENT_USER_TYPE,
    CURRENT_ELEMENT_NAME, CHOSEN_LOCALE, CHOSEN_ITEM
}
